version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:5000"
    depends_on:
      - db
    environment:
      ConnectionStrings__DefaultConnection: "Server=db;Database=BackEnd;User Id=sa;Password=YourStrongPassword123!;TrustServerCertificate=True;"
      ASPNETCORE_URLS: "http://+:5000"
      ASPNETCORE_ENVIRONMENT: "Development"

    networks:
      - BackEnd_network

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: BackEndDb
    restart: no
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrongPassword123!
      - MSSQL_DB=BackEnd
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - BackEnd_network

networks:
  BackEnd_network:

volumes:
  mssql_data:
